# Generated by Django 3.1.7 on 2021-03-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210325_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, upload_to='post_pics'),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(blank=True, choices=[('happy', 'happy'), ('sad', 'sad'), ('cheerful', 'cheerfu;')], max_length=20),
        ),
    ]
